# Generated by Django 4.1.12 on 2023-10-24 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=100)),
                ('last_trade_profit', models.IntegerField(default=0)),
                ('total_profit', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_trade_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
